
const WIDTH = 1080;
const HEIGTH = 1920;
HALF_X = WIDTH/2
let JSON_INDEX = 0;

const ANIMATION_TIME = 5000;
const ANIMATION_DURATION = 1000;
const TOGGLE_INTERVAL = 100; 


let HOME_BOX_COLOR = { r: 255, g: 0, b: 0, a: 180 };
let AWAY_BOX_COLOR = { r: 0, g: 0, b: 255, a: 180 };
let HOME_BOX_TEXT_COLOR = { r: 255, g: 255, b: 255, a: 255 };
let AWAY_BOX_TEXT_COLOR = { r: 255, g: 255, b: 255, a: 255 };

const MATCH_COMMENTARY_BOX_X = 0;
const MATCH_COMMENTARY_BOX_Y = 0;
const MATCH_COMMENTARY_BOX_WIDTH = WIDTH;
const MATCH_COMMENTARY_BOX_HEIGHT = 180;
let MATCH_COMMENTARY_BOX_COLOR = {r: 255, g: 208, b: 0, a: 255 };

const MATCH_COMMENTARY_TEXT_Y = MATCH_COMMENTARY_BOX_Y + MATCH_COMMENTARY_BOX_HEIGHT / 2;
const MATCH_COMMENTARY_TEXT_COLOR = {r: 0, g: 0, b: 0, a: 255 };


const LOGO_MARGIN_TOP = 55;
const LOGO_IMAGE_Y =  MATCH_COMMENTARY_BOX_Y + MATCH_COMMENTARY_BOX_HEIGHT + LOGO_MARGIN_TOP; // 230 + MARGİN           
const LOGO_IMAGE_WIDTH = 250;   
const LOGO_IMAGE_HEIGHT = 250;       
const LOGO_HOME_IMAGE_X = HALF_X/2 - LOGO_IMAGE_WIDTH/2
const LOGO_AWAY_IMAGE_X = HALF_X + HALF_X/2 - LOGO_IMAGE_WIDTH/2


const LOGO_BOX_Y = LOGO_IMAGE_Y + LOGO_IMAGE_HEIGHT/2
const LOGO_HOME_BOX_X = 0
const LOGO_AWAY_BOX_X = HALF_X
const LOGO_BOX_WIDTH = HALF_X
const LOGO_BOX_HEIGHT = 320

const HOME_MARGIN_TOP = 55
let HOME_NAME_COLOR = {r: 255, g: 255, b: 255, a: 255};
let AWAY_NAME_COLOR = {r: 255, g: 255, b: 255, a: 255};
const TEAM_NAME_Y = LOGO_IMAGE_Y + LOGO_IMAGE_HEIGHT + HOME_MARGIN_TOP
const HOME_NAME_X = HALF_X/2  
const AWAY_NAME_X = HALF_X + HALF_X/2


const SCORE_MARGIN_TOP = 85
let SCORE_HOME_COLOR = {r: 255, g: 255, b: 255, a: 255};
let SCORE_AWAY_COLOR = {r: 255, g: 255, b: 255, a: 255};
const SCORE_TEAM_Y = TEAM_NAME_Y + SCORE_MARGIN_TOP
const SCORE_HOME_X = HALF_X/2  
const SCORE_AWAY_X = HALF_X + HALF_X/2


const MATCH_DATE_BOX_COLOR = {r:0, g:0, b:0, a:120}
const MATCH_DATE_BOX_Y = LOGO_BOX_Y + LOGO_BOX_HEIGHT
const MATCH_DATE_BOX_HEIGHT = 60
const MATCH_DATE_BOX_WIDTH = WIDTH
const MATCH_DATE_BOX_X = 0


const MATCH_SQUAD_Y = MATCH_DATE_BOX_Y + MATCH_DATE_BOX_HEIGHT


