
const WIDTH = 1080;
const HEIGTH = 1920;
HALF_X = WIDTH/2
let JSON_INDEX = 0;

const ANIMATION_TIME = 5000;
const ANIMATION_DURATION = 1000;
const TOGGLE_INTERVAL = 100; 


const MATCH_DATE_BOX_COLOR = {r:0, g:0, b:0, a:60}
const MATCH_DATE_BOX_Y = 0
const MATCH_DATE_TEXT_FIRST_LINE_MARGIN_TOP = 3
const MATCH_DATE_TEXT_SECOND_LINE_MARGIN_TOP = 44 + MATCH_DATE_TEXT_FIRST_LINE_MARGIN_TOP
const MATCH_DATE_BOX_HEIGHT = 98
const MATCH_DATE_BOX_WIDTH = WIDTH
const MATCH_DATE_BOX_X = 0

const MATCH_COMMENTARY_BOX_MARGIN_TOP = 50
const MATCH_COMMENTARY_BOX_X = 0;
const MATCH_COMMENTARY_BOX_Y = MATCH_DATE_BOX_Y + MATCH_DATE_BOX_HEIGHT + MATCH_COMMENTARY_BOX_MARGIN_TOP
const MATCH_COMMENTARY_BOX_WIDTH = WIDTH;
const MATCH_COMMENTARY_BOX_HEIGHT = 180;
let MATCH_COMMENTARY_BOX_COLOR = {r: 255, g: 208, b: 0, a: 255 };





 
const LOGO_IMAGE_WIDTH = 180;   
const LOGO_IMAGE_HEIGHT = 180;
const LOGO_IMAGE_TOP = 40
const LOGO_IMAGE_Y =  MATCH_COMMENTARY_BOX_HEIGHT + MATCH_COMMENTARY_BOX_Y + LOGO_IMAGE_TOP
const LOGO_HOME_IMAGE_X = HALF_X/2 - LOGO_IMAGE_WIDTH/2
const LOGO_AWAY_IMAGE_X = HALF_X + HALF_X/2 - LOGO_IMAGE_WIDTH/2


let HOME_NAME_COLOR = {r: 255, g: 255, b: 255, a: 255};
let AWAY_NAME_COLOR = {r: 255, g: 255, b: 255, a: 255};
const NAME_MARGIN_TOP = 20
const TEAM_NAME_Y = LOGO_IMAGE_Y + LOGO_IMAGE_HEIGHT + NAME_MARGIN_TOP
const HOME_NAME_X = HALF_X/2 
const AWAY_NAME_X = HALF_X + HALF_X/2


const LOGO_BOX_MARGIN_TOP = 900;
const LOGO_BOX_Y = MATCH_COMMENTARY_BOX_Y + MATCH_COMMENTARY_BOX_HEIGHT
const LOGO_HOME_BOX_X = 0
const LOGO_AWAY_BOX_X = HALF_X
const LOGO_BOX_WIDTH = HALF_X
const LOGO_BOX_HEIGHT = 400

const SCORE_MARGIN_TOP = 90
let SCORE_HOME_COLOR = {r: 255, g: 255, b: 255, a: 255};
let SCORE_AWAY_COLOR = {r: 255, g: 255, b: 255, a: 255};
const SCORE_TEAM_Y = TEAM_NAME_Y + SCORE_MARGIN_TOP
const SCORE_HOME_X = HALF_X/2 
const SCORE_AWAY_X = HALF_X + HALF_X/2 

const ACTION_TITLE_MARGIN_TOP = 15
const ACTION_BOX_X = HALF_X;
const ACTION_BOX_Y = LOGO_BOX_Y + LOGO_BOX_HEIGHT
const MATCH_ACTION_BOX_HEIGHT = HEIGTH  - ACTION_BOX_Y 
const MATCH_ACTION_BOX_WIDTH =  WIDTH

const MATCH_COMMENTARY_TEXT_Y = MATCH_COMMENTARY_BOX_Y + MATCH_COMMENTARY_BOX_HEIGHT / 2;
const MATCH_COMMENTARY_TEXT_COLOR = {r: 0, g: 0, b: 0, a: 255 };

const MATCH_SQUAD_Y = ACTION_BOX_Y + ACTION_TITLE_MARGIN_TOP + 30
const MATCH_SQUAD_PADDING = 10
const MATCH_SQUAD_JERSEY_BOX_WIDTH = 50
const MATCH_SQUAD_ROW_HEIGHT = 60

let HOME_BOX_COLOR = { r: 255, g: 0, b: 0, a: 160 };
let AWAY_BOX_COLOR = { r: 0, g: 0, b: 255, a: 160 };
let HOME_BOX_TEXT_COLOR = { r: 255, g: 255, b: 255, a: 255 };
let AWAY_BOX_TEXT_COLOR = { r: 255, g: 255, b: 255, a: 255 };





















